TRUNCATE TABLE products;

INSERT INTO products (name, price, description, in_stock) VALUES
('Wireless Charger', 999.00, 'Fast charging Qi pad', true),
('Bluetooth Speaker Mini', 1799.00, 'Portable 10W speaker', true),
('External HDD 1TB', 4200.00, 'USB 3.0 portable drive', true),
('External SSD 512GB', 6200.00, 'High speed solid state drive', true),
('Laptop Backpack', 2100.00, 'Water resistant with padding', true),
('Gaming Chair', 13500.00, 'Ergonomic lumbar support', false),
('Desk Lamp LED', 750.00, 'Touch control brightness', true),
('Power Bank 20000mAh', 1999.00, 'Dual USB fast charge', true),
('Smartwatch Series Fit', 8999.00, 'Heart rate and sleep tracking', true),
('Fitness Band Lite', 2499.00, 'Step counter with OLED display', true),
('HDMI Cable 2m', 299.00, 'High speed braided cable', true),
('Ethernet Cable Cat6', 199.00, '1 Gbps network cable', true),
('Wireless Router AC1200', 3200.00, 'Dual band WiFi router', true),
('Mechanical Pencil', 49.00, '0.5mm HB lead pencil', true),
('Office Mouse Pad', 199.00, 'Non slip rubber base', true),
('Graphic Tablet Small', 5400.00, 'Pen tablet for drawing', true),
('USB Flash Drive 64GB', 699.00, 'Metal body pendrive', true),
('USB Flash Drive 128GB', 1199.00, 'High speed storage', false),
('Microphone Condenser', 4500.00, 'Studio quality recording mic', true),
('Pop Filter', 399.00, 'Noise reduction filter', true),
('Laptop Cooling Pad', 1299.00, 'Dual fan cooling system', true),
('Portable Projector', 22500.00, 'Full HD mini projector', false),
('Desk Organizer', 349.00, 'Multi compartment holder', true),
('Wireless Earbuds', 3200.00, 'Touch controls with case', true),
('Gaming Controller', 2899.00, 'Dual vibration feedback', true),
('Action Camera 4K', 15500.00, 'Waterproof sports cam', true),
('Tripod Stand Pro', 2100.00, 'Aluminum extendable tripod', true),
('Laptop Sleeve 15inch', 899.00, 'Shockproof padded cover', true),
('Keyboard Wrist Rest', 299.00, 'Memory foam support', true),
('Cable Management Box', 599.00, 'Hide power strips neatly', true),
('Smart Plug WiFi', 1099.00, 'App controlled switch', true),
('Surge Protector 6 Socket', 899.00, 'Overload protection', true),
('Desk Fan Mini', 499.00, 'USB powered fan', true),
('Portable Scanner', 9800.00, 'Handheld document scanner', false),
('Laser Pointer Presenter', 699.00, 'Wireless presentation remote', true),
('Monitor Arm Single', 4500.00, 'Adjustable gas spring mount', true),
('Standing Desk Converter', 17500.00, 'Height adjustable desk riser', true),
('Whiteboard Small', 799.00, 'Magnetic dry erase board', true),
('Printer Ink Cartridge Black', 1499.00, 'High yield ink', true),
('Printer Ink Cartridge Color', 1699.00, 'Tri color ink pack', false),
('Wireless Keyboard Slim', 2499.00, 'Low profile silent keys', true),
('USB Docking Station', 7500.00, 'Multi port laptop dock', true),
('Smart Light Bulb RGB', 799.00, 'App controlled color light', true),
('VR Headset Basic', 6200.00, 'Immersive mobile VR headset', true),
('Memory Card 128GB', 1399.00, 'Class 10 microSD', true),
('Car Phone Holder', 349.00, 'Dashboard mount stand', true),
('Screen Cleaning Kit', 199.00, 'Spray with microfiber cloth', true),
('Portable Label Printer', 4200.00, 'Bluetooth label maker', false),
('Desk Clock Digital', 599.00, 'LED alarm clock', true),
('Noise Reduction Panels', 2800.00, 'Acoustic foam set of 12', true);